CC = gcc
CFLAGS = -I../include -c
LFLAGS = -L../lib -lpthread -lmath
TARGET = aaa
OBJS = main.o

$(TARGET) : $(OBJS) 
	$(CC) $(OBJS) -o $(TARGET) $(LFLAGS) 

%.o : %.c
	$(CC) $(CFLAGS) $<

clean :
	rm -f $(OBJS) $(TARGET)
